------------------------VISTAS
create or alter view consulta_general as
                SELECT 
                row_number () OVER (ORDER BY CM.FECHAHORA) AS num,
                P.NOMBRE PACIENTE, P.FECHA_NACIMIENTO, 
                P.DIRECCION, C.NOMBRE CIUDAD_PACIENTE, D.NOMBRE DOCTOR, cd.nombre ciudad_doctor, E.NOMBRE ESPECIALIDAD,
                CM.FECHAHORA,
                COALESCE(DI.DESCRIPCION,'S/I') DESCRIPCION, COALESCE(DI.TRATAMIENTO,'S/I') TRATAMIENTO
                FROM MEDICITY_A.DBO.CITA_MEDICA_SA CM
                INNER JOIN MEDICITY_A.DBO.PACIENTE_SA P ON P.ID = CM.ID_PACIENTE
                INNER JOIN LS_SITIO_B.MEDICITY_B.DBO.DOCTOR_SB D ON D.ID = CM.ID_DOCTOR
                INNER JOIN MEDICITY_A.DBO.CIUDAD_SA C ON C.ID = P.ID_CIUDAD
                INNER JOIN MEDICITY_A.DBO.CIUDAD_SA CD ON CD.ID = D.ID_CIUDAD
                INNER JOIN LS_SITIO_B.MEDICITY_B.DBO.ESPECIALIDAD_SB E ON E.ID = D.ID_ESPECIALIDAD
                LEFT JOIN LS_SITIO_B.MEDICITY_B.DBO.DIAGNOSTICO_SB DI ON DI.ID_CITA = CM.ID;

        select * from consulta_general

----------------
CREATE VIEW vista_cita_medica AS
SELECT 
    P.NOMBRE AS PACIENTE, 
    D.NOMBRE AS DOCTOR, 
    CM.FECHAHORA
FROM MEDICITY_A.DBO.CITA_MEDICA_SA CM
INNER JOIN MEDICITY_A.DBO.PACIENTE_SA P ON P.ID = CM.ID_PACIENTE
INNER JOIN LS_SITIO_B.MEDICITY_B.DBO.DOCTOR_SB D ON D.ID = CM.ID_DOCTOR;

SELECT * FROM vista_cita_medica;


--- CREAMOS LA VITA PARA DIAGNOSTICO

CREATE VIEW vista_diagnostico AS
SELECT 
    D.NOMBRE AS NOMBRE_DIAGNOSTICO, 
    D.DESCRIPCION AS DESCRIPCION,
    D.TRATAMIENTO AS TRATAMIENTO
FROM LS_SITIO_B.MEDICITY_B.DBO.DIAGNOSTICO_SB  D

SELECT * FROM vista_diagnostico;

--------------
ALTER VIEW vista_paciente AS
SELECT 
    P.NOMBRE AS NOMBRE_PACIENTE,
    DATEDIFF(YEAR, P.FECHA_NACIMIENTO, GETDATE()) AS EDAD,
    P.DIRECCION AS DIRECCION,
    C.NOMBRE AS CIUDAD_PACIENTE
FROM MEDICITY_A.DBO.PACIENTE_SA P
INNER JOIN MEDICITY_A.DBO.CIUDAD_SA C ON C.ID = P.ID_CIUDAD
 SELECT * FROM vista_paciente;

------------
CREATE VIEW vista_doctores AS
SELECT 
    D.NOMBRE AS NOMBRE, 
    E.NOMBRE AS ESPECIALIDAD, 
    C.NOMBRE AS CIUDAD_DOCTOR
FROM LS_SITIO_B.MEDICITY_B.DBO.DOCTOR_SB D
INNER JOIN MEDICITY_A.DBO.CIUDAD_SA C ON C.ID = D.ID_CIUDAD
INNER JOIN LS_SITIO_B.MEDICITY_B.DBO.ESPECIALIDAD_SB E ON E.ID = D.ID_ESPECIALIDAD;

SELECT * FROM vista_doctores;